version: "3"
services:
  backend:
    build:
      context: backend
      target: dev
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5000:3030 # Map the app's ports as needed
      - 9229:9229
    depends_on:
      - db
    networks:
      - express-mongo
    volumes:
      - ./backend:/usr/src/app

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    expose:
      - 27017
    networks:
      - express-mongo

volumes:
  mydata:

networks:
  express-mongo:
